const mockJobs = [
  {
    title: 'Software Engineer',
    company: 'MockTech',
    location: 'Bengaluru, Karnataka, India',
    lat: 12.9716,
    lng: 77.5946,
    salary: '₹10–15 LPA',
    weight: 3,
  },
  {
    title: 'Full Stack Developer',
    company: 'DemoCorp',
    location: 'Pune, Maharashtra, India',
    lat: 18.5204,
    lng: 73.8567,
    salary: '₹8–12 LPA',
    weight: 2,
  },
  {
    title: 'Backend Developer',
    company: 'SampleWorks',
    location: 'Noida, Uttar Pradesh, India',
    lat: 28.5355,
    lng: 77.3910,
    salary: '₹7–11 LPA',
    weight: 1,
  },
  {
    title: 'Frontend Engineer',
    company: 'UI Labs',
    location: 'Hyderabad, Telangana, India',
    lat: 17.3850,
    lng: 78.4867,
    salary: '₹9–13 LPA',
    weight: 2,
  },
  {
    title: 'SDE 1',
    company: 'CloudWorks',
    location: 'Gurugram, Haryana, India',
    lat: 28.4595,
    lng: 77.0266,
    salary: '₹12–18 LPA',
    weight: 3,
  },
  {
    title: 'Data Engineer',
    company: 'DataFlow',
    location: 'Bengaluru, Karnataka, India',
    lat: 12.9716,
    lng: 77.5946,
    salary: '₹14–20 LPA',
    weight: 2,
  },
  {
    title: 'MERN Stack Developer',
    company: 'StartupHub',
    location: 'Pune, Maharashtra, India',
    lat: 18.5204,
    lng: 73.8567,
    salary: '₹7–10 LPA',
    weight: 1,
  },
  {
    title: 'DevOps Engineer',
    company: 'PipeOps',
    location: 'Chennai, Tamil Nadu, India',
    lat: 13.0827,
    lng: 80.2707,
    salary: '₹11–16 LPA',
    weight: 2,
  },
  {
    title: 'Security Engineer',
    company: 'SecureLayer',
    location: 'Delhi, Delhi, India',
    lat: 28.7041,
    lng: 77.1025,
    salary: '₹12–19 LPA',
    weight: 2,
  },
  {
    title: 'Junior Software Engineer',
    company: 'CodeBase',
    location: 'Kolkata, West Bengal, India',
    lat: 22.5726,
    lng: 88.3639,
    salary: '₹5–8 LPA',
    weight: 1,
  },
  {
    title: 'Android Developer',
    company: 'AppNation',
    location: 'Ahmedabad, Gujarat, India',
    lat: 23.0225,
    lng: 72.5714,
    salary: '₹6–9 LPA',
    weight: 1,
  },
  {
    title: 'Machine Learning Engineer',
    company: 'ML Labs',
    location: 'Bengaluru, Karnataka, India',
    lat: 12.9716,
    lng: 77.5946,
    salary: '₹15–22 LPA',
    weight: 3,
  },
  {
    title: 'SDE Intern',
    company: 'Internify',
    location: 'Hyderabad, Telangana, India',
    lat: 17.3850,
    lng: 78.4867,
    salary: '₹25K–40K / month',
    weight: 1,
  },
  {
    title: 'QA Engineer',
    company: 'QualityFirst',
    location: 'Pune, Maharashtra, India',
    lat: 18.5204,
    lng: 73.8567,
    salary: '₹5–8 LPA',
    weight: 1,
  },
  {
    title: 'Site Reliability Engineer',
    company: 'ReliStack',
    location: 'Gurugram, Haryana, India',
    lat: 28.4595,
    lng: 77.0266,
    salary: '₹13–20 LPA',
    weight: 2,
  },
];

export default mockJobs;
